### ISSUE TITLE
楼主，markdown部分格式出错。

### ISSUE THREAD

**Issue by ouyanmao** [yujiangshui/An-English-Guide-for-Programmers#3]
"# 听力识别器
"# 视力识别器
"# 理解器
"# 口语表达器
"# 书写表达器   "
.......是一级标题吗

**Comment by ouyanmao** [comment]
"# 书写表达器    。。。。等明细是一级标题对吧"

**Comment by yujiangshui** [comment]
不是，是 #### 四级标题居然比加粗字体还小，所以找了个标记来区分加粗字体，突出成小标题。无奈。
