### ISSUE TITLE
pte考试和真实英语水平

### ISSUE THREAD

**Issue by mioyuan** [yujiangshui/An-English-Guide-for-Programmers#5]
同意楼主说的，PTE题型设置合理，交叉评分的初衷确实是考察综合实力。但机考的弊端是备考技巧（可钻的空子）太多，此外还容易受外部因素影响，比如录音过程中音调过高甚至打喷嚏都会影响口语成绩。如果纯靠自己能力去考，确实能在一定程度上反应基础水平，但一旦用过机经、模板和技巧，就不适合作为评价的标准了。

个人觉得PTE更适合用来作为硬件申请，因为可以短期内大幅提高分数。如果想通过考试了解自己的能力，可能雅思结果更符合真实水平。

**Comment by yujiangshui** [comment]
我改进了一些说法： https://github.com/yujiangshui/An-English-Guide-for-Programmers/commit/12cfbb9083b5c560be131eae3664ceb410088968 

我部分认同你的观点。

PTE 的应试技巧能提的分也没有想象中的多，最开始看技巧视频我也觉得很简单，但实际用鸡精训练的时候你会发现老师讲得 case 很难遇到或者是陷阱。像 RL 或者 SST 这种技巧一般是套模版，但主要得分点还是要你能听出大意和一些关键词才可以。WFD、RS 会有一些鸡精命中率，但高命中概率的前提是练熟上百甚至几百条的句子，真练熟了之后其实能力也会提升上去的。更别提加分大户 RA，这个不是很短期就能练好的，实际考试考 RA 的时候环境十分嘈杂，耳机又听不到自己说的是什么，所以整个考试都是无意识看到啥说啥根本不知道自己在说什么，也不知道对错。

至于外部影响这个没办法的，不过也看个人，考雅思口语，有的人还面对老外就紧张或者被老外的情绪、口音所影响。再加上传闻的国内压分现象（身边有朋友去国外才考过的），所以我**个人主观的认为** PTE 评分部分相对客观一点，所以得出推荐 PTE 的结论。

我看楼主也在准备 PTE，推荐关注萤火虫公众号用他们近期高频鸡精来练，在我考的时候命中了一些。

**Comment by yujiangshui** [comment]
正解。只靠背肯定不行。SWT 这个我特别有感受，一开始是看不懂写不出来的，但是一直没时间练。到了最后考试前，参加了黑科技的复习打卡团，有一天是 SWT 就做了下，突然就感觉结构很清晰，顺着看下来就把重点摘出来了，信心就增加了很多。我做 Re-order Paragraph 做的多，估计跟这个有关系。

黑科技最好不要用小程序，Web 版更好用，更接近真实考试场景操作，一个月才 90 块也不贵。
