### ISSUE TITLE
大神，全片没有讲语法怎么学，是我太渣 了？

### ISSUE THREAD

**Issue by leirenjieyi** [yujiangshui/An-English-Guide-for-Programmers#6]

**Comment by yujiangshui** [comment]
没有，是我太渣了，还没怎么系统学过语法，没法写经验，都是专项遇到了去搜搜解决一小块疑问。

好像最近有篇很多人推荐的大神写的语法文章 http://www.yinwang.org/blog-cn/2018/11/23/grammar 可以看看。
